/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/van_gogh_room.glb 
Author: Sketchfab (https://sketchfab.com/Sketchfab)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/camera-limits-demo-van-gogh-bedroom-in-arles-daefab319a584e559443e39ff05e84fa
Title: Camera Limits Demo: Van Gogh - Bedroom in Arles
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/van_gogh_room.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.005}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['13___Default']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['13___Defaultdddddd']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['13___Defaultdddddddddddddd']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['13___Defaultddddddddddddddddddd']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['13___Defaultdddddddddddddddddddd']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['13___Defaultd']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['13___Defaultddd']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['13___Defaultddddd']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['13___Defaultdddddddd']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['13___Defaultdddddddd']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['13___Defaultddddddddd']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['13___Defaultddddddddddd']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['13___Defaultdddddddddddd']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['13___Defaultddddddddddddd']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['13___Defaultddddddddddddddd']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['13___Defaultdddddddddddddddd']} />
      </group>
    </group>
  )
}

useGLTF.preload('/van_gogh_room.glb')
